<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath().'/css/admin/login.css')  
        ?>                       
    </head>
    <body id="login">

        <div id="sitewrapper">
            <div id="header">
                <a id="logo" href="http://www.lacucharabrava.com/"></a>
            </div>
            <div id="content">
                <div id="main">
                    <?php echo $this->content; ?>                                        
                </div>
            </div>
        </div>            
    </body>
</html>