<div id="forgot-password-flash" class="flash bad" style="display:none;">
    <div class="inner">
        <h3>Did you forget your password?</h3>
        Shame shame shame... Not really - It's actually no problem at all. Just enter your email in the box below and we'll send it right along.
    </div>
</div>
<h1>Acceso Administrador</h1>
<form name="login" action="../admin-mavery/index.php" method="post">
    <div id="email">
        <fieldset id="user-email">
            <p><label>Usuario:<span><input type="text" name="login" value="" tabindex="1"></span></label></p>
        </fieldset>
    </div>
    <div id="password">
        <fieldset id="user-password">
            <p>
                <strong>Oops - <a href="../admin-mavery/login.php?action=recuperar_c">Olvidé mi contraseña</a></strong>
                <label>Password:<span><input type="password" value="" name="password" tabindex="2"></span></label>
            </p>
        </fieldset>
        <p>
            <label id="remember-password"><input name="recordar_si_MKD" value="si" type="checkbox">Recordarme por 30 días</label>
            <input type="image" id="sign-in" name="enviar" src="<?php echo $this->basePath() ?>/imgs/admin/entrar.jpg" alt="Sign In" tabindex="3">
        </p>
    </div>
    <div id="forgot-password" style="display:none;">
        <input name="commit" type="submit" value="Email me my password"><label>Just kidding<a href="#" onclick="remember(); return false;">Recordarme por 30 días</a></label>
    </div>
</form>  