<div id="forgot-password-flash" class="flash bad" style="display:none;">
    <div class="inner">
        <h3>Did you forget your password?</h3>
        Shame shame shame... Not really - It's actually no problem at all. Just enter your email in the box below and we'll send it right along.
    </div>
</div>
<h1>Recuperar Contraseña</h1>
<form name="login" action="?action=acceso" method="post">
    <div id="email">
        <fieldset id="user-email">
            <p>
                <label>E-mail:<span><input type="text" name="login" tabindex="1"></span></label><br>
                <input type="image" src="../aplication/webroot/imgs/enviar.jpg" style="float:left; margin-right:20px">
                <label style="margin:20px 0 0 0"> <a href="../admin-mavery/login.php">Iniciar Sesión</a></label>
            </p>
        </fieldset>
    </div>
</form>  