<div class="left_footer"> 
    <img src="imgs/footer_logo.png" alt="" width="89" height="42"/> 
</div>
<div class="center_footer"> Template name. All Rights Reserved 2008<br />
    <a href="http://csscreme.com">
        <img src="imgs/csscreme.jpg" alt="csscreme" title="csscreme" border="0" />
    </a><br />
    <img src="imgs/payment.gif" alt="" /> 
</div>
<div class="right_footer"> 
    <a href="http://all-free-download.com/free-website-templates/">home</a> 
    <a href="http://all-free-download.com/free-website-templates/">about</a> 
    <a href="http://all-free-download.com/free-website-templates/">sitemap</a> 
    <a href="http://all-free-download.com/free-website-templates/">rss</a> 
    <a href="http://all-free-download.com/free-website-templates/">contact us</a> 
</div>