<ul class="menu">
    <li><a href="http://all-free-download.com/free-website-templates/" class="nav"> Home </a></li>
    <li class="divider"></li>
    <li><a href="http://all-free-download.com/free-website-templates/" class="nav">Products</a></li>
    <li class="divider"></li>
    <li><a href="http://all-free-download.com/free-website-templates/" class="nav">Specials</a></li>
    <li class="divider"></li>
    <li><a href="http://all-free-download.com/free-website-templates/" class="nav">My account</a></li>
    <li class="divider"></li>
    <li><a href="http://all-free-download.com/free-website-templates/" class="nav">Sign Up</a></li>
    <li class="divider"></li>
    <li><a href="http://all-free-download.com/free-website-templates/" class="nav">Shipping </a></li>
    <li class="divider"></li>
    <li><a href="contact.html" class="nav">Contact Us</a></li>
    <li class="divider"></li>
    <li><a href="details.html" class="nav">Details</a></li>
</ul>