<ul class="menu">
    <li><a href="" class="nav">Inicio</a></li>
    <li class="divider"></li>
    <li><a href="" class="nav">Productos</a></li>
    <li class="divider"></li>
    <li><a href="" class="nav">Servicios</a></li>
    <li class="divider"></li>
    <li><a href="" class="nav">Tutoriales</a></li>
    <li class="divider"></li>
    <li><a href="" class="nav">Noticias y eventos</a></li>
    <li class="divider"></li>
    <li><a href="" class="nav">Contacto</a></li>
</ul>