<div class="title_box">Categories</div>
<ul class="left_menu">
  <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Power Tools</a></li>
  <li class="even"><a href="http://all-free-download.com/free-website-templates/">Air Tools</a></li>
  <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Hand Tools</a></li>
  <li class="even"><a href="http://all-free-download.com/free-website-templates/">Accessories</a></li>
  <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Workwear</a></li>
  <li class="even"><a href="http://all-free-download.com/free-website-templates/">Spare Parts</a></li>
  <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Power Tools</a></li>
  <li class="even"><a href="http://all-free-download.com/free-website-templates/">Air Tools</a></li>
  <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Hand Tools</a></li>
  <li class="even"><a href="http://all-free-download.com/free-website-templates/">Accessories</a></li>
  <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Workwear</a></li>
  <li class="even"><a href="http://all-free-download.com/free-website-templates/">Spare Parts</a></li>
</ul>
<div class="title_box">Special Products</div>
<div class="border_box">
  <div class="product_title">
    <a href="http://all-free-download.com/free-website-templates/">Makita 156 MX-VL</a>
  </div>
  <div class="product_img">
    <a href="http://all-free-download.com/free-website-templates/">
      <img src="imgs/p1.jpg" alt="" border="0">
    </a>
  </div>
  <div class="prod_price">
    <span class="reduce">350$</span> 
    <span class="price">270$</span>
  </div>
</div>
<div class="title_box">Newsletter</div>
<div class="border_box">
  <input type="text" name="newsletter" class="newsletter_input" value="your email">
  <a href="http://all-free-download.com/free-website-templates/" class="join">subscribe</a> 
</div>
<div class="banner_adds"> 
  <a href="http://all-free-download.com/free-website-templates/"><img src="imgs/bann2.jpg" alt="" border="0"></a> 
</div>