<h1>Recuperar Contraseña</h1>
<form name="login" action="?action=acceso" method="post">
    <div id="email">
        <fieldset id="user-email">
            <p>
                <label>E-mail:<span><input type="text" name="login" tabindex="1"></span></label><br>
                <input type="image" src="<?php echo $this->basePath() ?>/imgs/admin/enviar.jpg" style="float:left; margin-right:20px">
                <label style="margin:20px 0 0 0"> 
                    <a href="<?php echo $this->basePath() ?>/admin/cuenta">Iniciar Sesión</a>
                </label>
            </p>
        </fieldset>
    </div>
</form>  