<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2') ?>
    <?php echo $this->headMeta()->appendName('keywords', 'framework, PHP, productivity');?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headLink()->prependStylesheet($this->basePath().'/css/style.css') ?>
    <?php echo $this->headScript()->appendFile($this->basePath().'/js/boxOver.js') ?>
  </head>
  <body>
    <div id="main_container">
      <div id="header">
        <?php echo $this->partial('layout/banner') ; ?>
      </div>
      <div id="main_content">
        <div id="menu_tab">
          <?php echo $this->partial('layout/menu') ; ?>
        </div>
        <div class="crumb_navigation"> Navigation: <span class="current">Home</span> </div>
        <div class="left_content">
          <?php echo $this->partial('layout/panel_left') ; ?>
        </div>
        <div class="center_content">
          <?php echo $this->content; ?>
        </div>
        <div class="right_content">
          <?php echo $this->partial('layout/panel_right') ; ?>
        </div>
      </div>
      <div class="footer">
        <?php echo $this->partial('layout/footer') ; ?>
      </div>
    </div>
  </body>
</html>